# Generated by Django 6.0 on 2025-12-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена')),
                ('image', models.URLField(verbose_name='Картинка')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Состав')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('login', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('gender', models.CharField(choices=[('woman', 'Женский'), ('man', 'Мужской'), ('none-gender', 'Не указан')], max_length=20, verbose_name='Пол')),
                ('role', models.CharField(choices=[('standart', 'Стандарт'), ('blocked', 'Заблокирован'), ('junior-admin', 'Младший администратор'), ('adult-admin', 'Старший администратор')], default='standart', max_length=20, verbose_name='Роль')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
