# Generated by Django 6.0 on 2025-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(default=' ', upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
